travis:
  secure:
    BINSTAR_TOKEN: QF6DMyUD0WtUEk7m0X4RfqBfqPbGwezmvZA3ViFSuXJBVEPlawmOvaFUa9RqbxsptBawp3ismJ6twvPCAk/yichPwMMUjsGHnLYBm29AYjL3HmKxYIAhf/1n/te0u9c4pvXDQObhZXUVv9sjp1itYBzEJcV0Ubi52VU/U9WoqyK2E7D3PsL/runIapCw+nqfUSGQqTCxIjlV/o11elANZHOO0DdXTdUlm2sshydNFXx8nwxdpWOg7HbWnVyDISlLyOYXsDoIR38qio17EKmqVUQm9A1YiIO2mIWd5w2oyBUQeZ+UYHwSC/XdkSCoHvGyA0nVe0bplPDalBDx1XRs/8bWZF80orsdLp2bJTzMr1AmyK36BJGzqYgCXL2+Gpb+cORNeqHp8tt+UhLRxPyCby7WRWI9vamLQIN6FWpJwAQO7MmlpS5z2LGmVr/yVoJUOBE1UIKwoFtmOP+jtR7utaLLTVCu4fK4D/PUeDK+2WylWEbDAGJCFJvW8cVQZeosbOi/yOHBSSxCueA4ZTYcBcSGBh1jCPKGvUIVUEansV1sMksTzhItTQ/Nm2zKICXS+vMyUJw7FSY96yMvTtfNe0rUZp8EV3mjUPBsQc6VZHPJIrCvB+qVvOiR9EJjIz5pUStS3uOQg4Y+47UOubDVWJDCwOhkEo0mvveuFU+2obI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
